# Generated by Django 3.0.5 on 2020-04-02 23:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendido', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=200)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('disponibilidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tendero',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='tendero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Tendero'),
        ),
    ]
